---
# -*- coding: utf-8 -*-

before_script:
  - env
  - hostname
  - ip r
  - du --max-depth=1
  - uname -a
  - ansible --version
  - ansible-lint --version
  - awx-cli --version

stages:
  - ansible-lint
  - ansible-syntax-check

ansible-lint:
  stage: ansible-lint
  script:
    - make lint
  tags:
    - ansible

ansible-syntax-check:
  stage: ansible-syntax-check
  script:
    - make syntax
  tags:
    - ansible
