---

- name: (freeipa-sssd-tools) define freeipa_sssd_tools_config_ldb_host
  set_fact:
    freeipa_sssd_tools_config_ldb_host: "/var/lib/sss/db/cache_{{ freeipa_sssd_tools_config_ipa_domain }}.ldb"
  when: freeipa_sssd_tools_config_ipa_domain | length > 0

- name: (freeipa-sssd-tools) set .ipa-config
  template:
    src: templates/ipa-config.j2
    dest:  "{{ freeipa_sssd_tools_config_file }}"
    owner: "{{ freeipa_sssd_tools_config_owner }}"
    group: "{{ freeipa_sssd_tools_config_group }}"
    mode:  "{{ freeipa_sssd_tools_config_mode }}"
  become: yes

- name: (freeipa-sssd-tools) set ipa-sss-plt.cfg
  template:
    src: templates/ipa-sss-plt.cfg.j2
    dest:  "{{ freeipa_sssd_tools_httpd_syn_plt_conf }}"
    owner: "{{ freeipa_sssd_tools_config_owner }}"
    group: "{{ freeipa_sssd_tools_config_group }}"
    mode:  "{{ freeipa_sssd_tools_config_mode }}"
    become: yes

- name: (freeipa-sssd-tools) ensure ipa-sss-syn.log exists
  file:
    path: "{{ freeipa_sssd_tools_config_log_file }}"
    owner: "{{ freeipa_sssd_tools_log_owner }}"
    group: "{{ freeipa_sssd_tools_log_group }}"
    mode:  "{{ freeipa_sssd_tools_log_mode }}"
    state: touch
  become: yes

- name: (freeipa-sssd-tools) ensure ipa-sss-syn.err exists
  file:
    path: "{{ freeipa_sssd_tools_config_log_error }}"
    owner: "{{ freeipa_sssd_tools_log_owner }}"
    group: "{{ freeipa_sssd_tools_log_group }}"
    mode:  "{{ freeipa_sssd_tools_log_mode }}"
    state: touch
  become: yes

- name: (freeipa-sssd-tools) set ipa-api-config
  template:
    src: templates/ipa-api-config.j2
    dest:  "{{ freeipa_sssd_tools_api_config_file }}"
    owner: "{{ freeipa_sssd_tools_api_config_owner }}"
    group: "{{ freeipa_sssd_tools_api_config_group }}"
    mode:  "{{ freeipa_sssd_tools_api_config_mode }}"
  become: yes
  when: freeipa_sssd_tools_api_config_api | bool

- name: (freeipa-sssd-tools) set uwsgi.ini
  template:
    src: templates/ipa-api_uwsgi.j2
    dest:  "{{ freeipa_sssd_tools_api_uwsgi_ini }}"
    owner: "{{ freeipa_sssd_tools_api_config_owner }}"
    group: "{{ freeipa_sssd_tools_api_config_group }}"
    mode:  "{{ freeipa_sssd_tools_api_config_mode }}"
  become: yes
  when: freeipa_sssd_tools_api_uwsgi_config | bool

- name: (freeipa-sssd-tools) ensure ipa-api-que-syn permissions
  file:
    path:  "{{ freeipa_sssd_tools_api_que_syn_bin }}"
    owner: "{{ freeipa_sssd_tools_api_que_syn_user }}"
    group: "{{ freeipa_sssd_tools_api_que_syn_group }}"
    mode:  "{{ freeipa_sssd_tools_api_que_syn_mode }}"
  become: yes
  when: freeipa_sssd_tools_api_config_que_syn | bool

- name: (freeipa-sssd-tools) set ipa-api-que-syn-config
  template:
    src: templates/ipa-api-que-syn-config.j2
    dest:  "{{ freeipa_sssd_tools_api_que_syn_config_file }}"
    owner: "{{ freeipa_sssd_tools_api_que_syn_config_owner }}"
    group: "{{ freeipa_sssd_tools_api_que_syn_config_group }}"
    mode:  "{{ freeipa_sssd_tools_api_que_syn_config_mode }}"
  become: yes
  when: freeipa_sssd_tools_api_config_que_syn | bool

- name: (freeipa-sssd-tools) set ipa-api-que-syn-config
  template:
    src: templates/ipa-api-que-syn-config.j2
    dest:  "{{ freeipa_sssd_tools_api_que_syn_config_file }}"
    owner: "{{ freeipa_sssd_tools_api_que_syn_config_owner }}"
    group: "{{ freeipa_sssd_tools_api_que_syn_config_group }}"
    mode:  "{{ freeipa_sssd_tools_api_que_syn_config_mode }}"
  become: yes
  when: freeipa_sssd_tools_api_config_que_syn | bool
