---

- name: (freeipa-sssd-tools) check directories defined in PATH of crontab
  command: "test -d {{ item }}"
  with_items: "{{ freeipa_sssd_tools_cron_path.split(':') }}"
  when: freeipa_sssd_tools_cron_path is defined

- name: (freeipa-sssd-tools) test ipa-usr-all to get users from LDAP/AD
  shell: ipa-usr-all
  args:
    executable: /bin/bash
  environment: "{{ freeipa_sssd_tools_cron_test_environment | default(omit) }}"
  no_log: "{{ freeipa_sssd_tools_cron_test_no_log | default(true) }}"
  register: ipa_usr_all_result
  become: yes
  when:
    - freeipa_sssd_tools_cron_test_ipa_usr_all is defined
    - freeipa_sssd_tools_cron_test_ipa_usr_all | bool

- name: (freeipa-sssd-tools) add PATH on top of crontab
  cron:
    name: PATH
    cron_file: freeipa-sssd-tools
    env: yes
    job: "{{ freeipa_sssd_tools_cron_path | default(mandatory) }}"
    user: "{{ freeipa_sssd_tools_username }}"
  become: yes
  when:
    - freeipa_sssd_tools_cron_path is defined
    - freeipa_sssd_tools_username is defined

- name: (freeipa-sssd-tools) cron jobs
  cron:
    name: "{{ item.name | default(omit) }}"
    cron_file: "{{ item.cron_file | default(mandatory) }}"
    day: "{{ item.day | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    job: "{{ item.job | default(mandatory) }}"
    minute: "{{ item.minute | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    user: "{{ freeipa_sssd_tools_username | default(mandatory) }}"
  become: yes
  when:
    - item.enabled is defined
    - item.enabled | bool
    - item.cron_file is defined
    - item.job is defined
    - item.user is defined
  with_items:
    - "{{ freeipa_sssd_tools_cron_entries }}"

- name: (freeipa-sssd-tools) restart service cron
  service:
    name: "{{ freeipa_sssd_tools_cron_service | default(mandatory) }}"
    state: restarted
  become: yes
  when: freeipa_sssd_tools_cron_restart | bool
