---

- name: (freeipa-sssd-tools) add PATH on top of crontab
  cron:
    name: PATH
    cron_file: freeipa-sssd-tools
    env: yes
    job: "{{ freeipa_sssd_tools_cron_path | default(mandatory) }}"
    user: "{{ freeipa_sssd_tools_username }}"
  become: yes
  when:
    - freeipa_sssd_tools_cron_path is defined
    - freeipa_sssd_tools_username is defined

- name: (freeipa-sssd-tools) cron jobs
  cron:
    name: "{{ item.name | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    job: "{{ item.job | default(mandatory) }}"
    cron_file: "{{ item.cron_file | default(omit) }}"
    env: "{{ item.env | default(omit) }}"
  become: yes
  when: item.enabled
  with_items:
    - "{{ freeipa_sssd_tools_cron_entries }}"

- name: (freeipa-sssd-tools) restart service cron
  service:
    name: cron
    state: restarted
  become: yes
  when: freeipa_sssd_tools_cron_restart | bool
