---

  - name: (freeipa_sssd_tools) split SynLog by date
    shell: "{{ freeipa_sssd_tools_log_day_cmd }}"
    args:
      executable: /bin/bash
    environment:
      PATH: "{{ freeipa_sssd_tools_dir }}:{{ ansible_env.PATH }}"
    when:
      - freeipa_sssd_tools_log_day is defined
      - freeipa_sssd_tools_log_day | bool
      - freeipa_sssd_tools_log_day_cmd is defined
      - freeipa_sssd_tools_log_day_cmd | length > 0

  - name: (freeipa_sssd_tools) filter SynLog with unsynchronized logs
    shell: "{{ freeipa_sssd_tools_log_nsy_cmd }}"
    args:
      executable: /bin/bash
    environment:
      PATH: "{{ freeipa_sssd_tools_dir }}:{{ ansible_env.PATH }}"
    when:
      - freeipa_sssd_tools_log_nsy is defined
      - freeipa_sssd_tools_log_nsy | bool
      - freeipa_sssd_tools_log_nsy_cmd is defined
      - freeipa_sssd_tools_log_nsy_cmd | length > 0

  - name: (freeipa_sssd_tools) filter SynLog when record date match with accountExpires date
    shell: "{{ freeipa_sssd_tools_log_exp_cmd }}"
    args:
      executable: /bin/bash
    environment:
      PATH: "{{ freeipa_sssd_tools_dir }}:{{ ansible_env.PATH }}"
    when:
      - freeipa_sssd_tools_log_exp is defined
      - freeipa_sssd_tools_log_exp | bool
      - freeipa_sssd_tools_log_exp_cmd is defined
      - freeipa_sssd_tools_log_exp_cmd | length > 0

  - name: (freeipa_sssd_tools) generate SynLog report for one day
    shell: "{{ freeipa_sssd_tools_log_log_cmd }}"
    args:
      executable: /bin/bash
    environment:
      PATH: "{{ freeipa_sssd_tools_dir }}:{{ ansible_env.PATH }}"
    when:
      - freeipa_sssd_tools_log_exp is defined
      - freeipa_sssd_tools_log_exp | bool
      - freeipa_sssd_tools_log_exp_cmd is defined
      - freeipa_sssd_tools_log_exp_cmd | length > 0

