---

  - name: (freeipa_sssd_tools) verify SynLog report exists
    stat:
      path: '{{ freeipa_sssd_tools_log_log_md }}'
    ignore_errors: true
    register: freeipa_sssd_tools_log_log_md_result

  - name: (freeipa_sssd_tools) view SynLog report for one day
    command: cat {{ freeipa_sssd_tools_log_log_md }}
    when:
      - freeipa_sssd_tools_log_log_view is defined
      - freeipa_sssd_tools_log_log_view
      - freeipa_sssd_tools_log_log_md_result is defined
      - freeipa_sssd_tools_log_log_md_result.stat.exists

  - name: (freeipa_sssd_tools) verify SynLog error exists
    stat:
      path: '{{ freeipa_sssd_tools_log_err_log }}'
    ignore_errors: true
    register: freeipa_sssd_tools_log_err_log_result

  - name: (freeipa_sssd_tools) view SynLog error
    command: cat {{ freeipa_sssd_tools_log_err_log }}
    when:
      - freeipa_sssd_tools_log_err_view is defined
      - freeipa_sssd_tools_log_err_view
      - freeipa_sssd_tools_log_err_log_result is defined
      - freeipa_sssd_tools_log_err_log_result.stat.exists

  - name: (freeipa_sssd_tools) verify SynLog error report exists
    stat:
      path: '{{ freeipa_sssd_tools_rpt_err_md }}'
    ignore_errors: true
    register: freeipa_sssd_tools_rpt_err_md_result

  - name: (freeipa_sssd_tools) view SynLog error report
    command: cat {{ freeipa_sssd_tools_rpt_err_log }}
    when:
      - freeipa_sssd_tools_rpt_err_view is defined
      - freeipa_sssd_tools_rpt_err_view
      - freeipa_sssd_tools_rpt_err_md_result is defined
      - freeipa_sssd_tools_rpt_err_md_result.stat.exists
