---

- name: (freeipa-sssd-tools) configure logrotate for ipa-sss-syn
  template:
    src: templates/logrotate.d/ipa-sss-syn.j2
    dest:  "{{ freeipa_sssd_tools_logrorate_dir }}"
    owner: "{{ freeipa_sssd_tools_logrorate_owner }}"
    group: "{{ freeipa_sssd_tools_logrorate_group }}"
    mode:  "{{ freeipa_sssd_tools_logrorate_mode }}"
  become: yes
  when: freeipa_sssd_tools_logrorate_ipa_sss_syn | length > 0
