---

- name: (freeipa_sssd_tools) include OS family variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: (freeipa_sssd_tools) include OS distribution variables
  include_vars: "{{ ansible_os_family }}_{{ ansible_distribution }}.yml"

- name: (freeipa_sssd_tools) include proxy tasks
  include_tasks: proxy.yml
  when: freeipa_sssd_tools_http_proxy_use | bool

- name: (freeipa_sssd_tools) include packages tasks
  include_tasks: packages.yml
  when: freeipa_sssd_tools_packages_install | bool

- name: (freeipa_sssd_tools) include git tasks
  include_tasks: git.yml
  when: freeipa_sssd_tools_git_clone | bool

- name: (freeipa_sssd_tools) ensure tools directory exists
  file:
    path:  "{{ freeipa_sssd_tools_dir }}"
    owner: "{{ freeipa_sssd_tools_dir_owner }}"
    group: "{{ freeipa_sssd_tools_dir_group }}"
    mode:  "{{ freeipa_sssd_tools_dir_mode  }}"
    state: directory
  become: yes

- name: (freeipa_sssd_tools) include ramdisk tasks
  include_tasks: ramdisk.yml
  when:
    - freeipa_sssd_tools_ramdisk_configure | bool

- name: (freeipa_sssd_tools) include python requirements tasks
  include_tasks: python-reqs.yml
  when:
    - freeipa_sssd_tools_api_deploy | bool
    - freeipa_sssd_tools_api_python_req | bool

- name: (freeipa_sssd_tools) include API user/group creation tasks
  include_tasks: api-users.yml
  when:
    - freeipa_sssd_tools_api_deploy | bool
    - freeipa_sssd_tools_api_create_usrgrp | bool

- name: (freeipa_sssd_tools) include permissions tasks
  include_tasks: permissions.yml
  when: freeipa_sssd_tools_set_permissions | bool

- name: (freeipa_sssd_tools) include config tasks
  include_tasks: config.yml
  when: freeipa_sssd_tools_config | bool

- name: (freeipa_sssd_tools) include cron tasks
  include_tasks: cron.yml
  when:
    - freeipa_sssd_tools_cron_configure | bool
    - freeipa_sssd_tools_cron_entries | length > 0

- name: (freeipa_sssd_tools) include logrotate tasks
  include_tasks: logrotate.yml
  when:
    - freeipa_sssd_tools_logrotate_configure | bool

- name: (freeipa_sssd_tools) include systemd tasks
  include_tasks: systemd.yml
  when:
    - freeipa_sssd_tools_api_deploy | bool
    - freeipa_sssd_tools_api_systemd | bool

- name: (freeipa_sssd_tools) include httpd tasks
  include_tasks: httpd.yml
  when:
    - freeipa_sssd_tools_httpd_syn_conf | bool

- name: (freeipa_sssd_tools) include test-syn tasks
  include_tasks: test-syn.yml
  when:
    - freeipa_sssd_tools_test | bool
    - freeipa_sssd_tools_test_users | length > 0
  loop: "{{ freeipa_sssd_tools_test_users }}"

- name: (freeipa_sssd_tools) execute health check
  shell: ipa-hlt-chk
  args:
    executable: /bin/bash
    chdir: "{{ freeipa_sssd_tools_dir }}"
  become: true
  when:
    - freeipa_sssd_tools_health_check | bool
