---

- name: (freeipa-sssd-tools) include yum-repos tasks
  include_tasks: yum-repos.yml
  when:
    - freeipa_sssd_tools_yum_repositories_configure | bool
    - freeipa_sssd_tools_yum_repositories | length > 0

- name: (freeipa-sssd-tools) include yum-dnf tasks
  include_tasks: yum-dnf.yml
  when:
    - freeipa_sssd_tools_etc_yum_dnf_files is defined
    - freeipa_sssd_tools_etc_yum_dnf_files | length > 0
  with_items:
    - "{{ freeipa_sssd_tools_etc_yum_dnf_files }}"

- name: (freeipa-sssd-tools) install python-pip
  yum:
    name: python-pip
    state: present
    update_cache: true
  become: yes

- name: (freeipa-sssd-tools) ensure required packages are installed
  package:
    name: "{{ freeipa_sssd_tools_packages }}"
    state: present
  become: yes
  when: freeipa_sssd_tools_packages | length > 0

- name: (freeipa-sssd-tools) ensure API required packages are installed
  package:
    name: "{{ freeipa_sssd_tools_api_packages }}"
    state: present
  become: yes
  when: freeipa_sssd_tools_api_packages | length > 0

- name: (freeipa-sssd-tools) ensure plot required packages are installed
  package:
    name: "{{ freeipa_sssd_tools_plot_packages }}"
    state: present
  become: yes
  when: freeipa_sssd_tools_plot_packages | length > 0
