---

- name: (freeipa-sssd-tools) force IPv4 in /etc/yum.conf
  lineinfile:
    path: /etc/yum.conf
    line: ip_resolve=4
    state: present
  become: yes
  when:
    - freeipa_sssd_tools_http_proxy_ipv4 | bool

- name: (freeipa-sssd-tools) enable proxy in /etc/yum.conf
  lineinfile:
    line: proxy={{ freeipa_sssd_tools_http_proxy_url }}
    path: /etc/yum.conf
    regexp: '^proxy.*$'
    state: present
  become: yes
  when:
    - freeipa_sssd_tools_http_proxy_use | bool
    - freeipa_sssd_tools_http_proxy_url | length > 0

- name: (freeipa-sssd-tools) install epel repository
  yum:
    name: epel-release
    state: present
  become: yes

- name: (freeipa-sssd-tools) ensure epel repo is enabled
  ini_file:
    dest: /etc/yum.repos.d/epel.repo
    section: epel
    option: enabled
    value: '1'
  become: yes

- name: (freeipa-sssd-tools) install python-pip
  yum:
    name: python-pip
    state: present
    update_cache: true
  become: yes

- name: (freeipa-sssd-tools) ensure required packages are installed
  package:
    name: "{{ freeipa_sssd_tools_packages }}"
    state: present
  become: yes
  when: freeipa_sssd_tools_packages | length > 0

- name: (freeipa-sssd-tools) ensure API required packages are installed
  package:
    name: "{{ freeipa_sssd_tools_api_packages }}"
    state: present
  become: yes
  when: freeipa_sssd_tools_api_packages | length > 0
