---

- name: (freeipa_sssd_tools) install ipa-api-syn python requirements
  pip:
    requirements: "{{ freeipa_sssd_tools_api_req_file_loc }}"
    state: forcereinstall
    umask: "0022"
  environment: "{{ freeipa_sssd_tools_http_proxy_env }}"
  when: freeipa_sssd_tools_ipa_req_file_loc is defined
