---

- name: (freeipa-sssd-tools) test ipa-sss-syn {{ item }}
  shell: "{{ freeipa_sssd_tools_dir }}/ipa-sss-syn {{ item }}"
  args:
    executable: /bin/bash
  environment: "{{ freeipa_sssd_tools_syn_environment }}"
  changed_when: False
  ignore_errors: True
  register: ipa_sss_syn_result
  become: yes

- name: (freeipa_sssd_tools) verify ipa-sss-syn {{ item }} critical error
  fail:
    msg: error ipa_sss_syn_result.rc
  when:
    - ipa_sss_syn_result is defined
    - ipa_sss_syn_result.rc | default('') in freeipa_sssd_tools_test_errors_critical

- name: (freeipa_sssd_tools) test ipa-api-syn sAMAccountName {{ item }}
  uri:
    url: "{{ freeipa_sssd_tools_api_uwsgi_test_syn }}/{{ item }}"
    method: GET
    status_code: 200
    return_content: yes
  register: ipa_api_syn_result
  become: no

- name: (freeipa_sssd_tools) verify ipa-api-syn retval sAMAccountName {{ item }}
  fail:
    msg: unknown error
  when:
    - ipa_api_syn_result is defined
    - ipa_api_syn_result.json.retval | default('') != 'OK'

- name: (freeipa_sssd_tools) test ipa-api-qry sAMAccountName {{ item }}
  uri:
    url: "{{ freeipa_sssd_tools_api_uwsgi_test_qry }}/{{ item }}"
    method: GET
    status_code: 200
    return_content: yes
  register: ipa_api_qry_result
  become: no

- name: (freeipa_sssd_tools) verify ipa-api-qry retval sAMAccountName {{ item }}
  fail:
    msg: unknown error
  when:
    - ipa_api_qry_result is defined
    - ipa_api_qry_result.json.retval | default('') != 'OK'
